{"name": "test_add_students_ddt_2", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'H:\\\\Git_projekty\\\\Api using python\\\\test_data.xlsx'", "trace": "def test_add_students_ddt_2():\n    \n        url = 'https://thetestingworldapi.com/api/studentsDetails'\n        f = open('H:/Git_projekty/Api using python/TestSMS/add_student_ddt.json', 'r')\n        json_request = json.loads(f.read())\n    \n>       obj = library.Common(os.path.abspath('test_data.xlsx'), 'Arkusz1')\n\nTestSMS\\DataDriven\\test_case.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nTestSMS\\DataDriven\\library.py:12: in __init__\n    wk = openpyxl.load_workbook(FileNamePath, SheetName)\nC:\\Users\\jacek\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\openpyxl\\reader\\excel.py:315: in load_workbook\n    reader = ExcelReader(filename, read_only, keep_vba,\nC:\\Users\\jacek\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\openpyxl\\reader\\excel.py:124: in __init__\n    self.archive = _validate_archive(fn)\nC:\\Users\\jacek\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\openpyxl\\reader\\excel.py:96: in _validate_archive\n    archive = ZipFile(filename, 'r')\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <zipfile.ZipFile [closed]>, file = 'H:\\\\Git_projekty\\\\Api using python\\\\test_data.xlsx', mode = 'r', compression = 0, allowZip64 = True\ncompresslevel = None\n\n    def __init__(self, file, mode=\"r\", compression=ZIP_STORED, allowZip64=True,\n                 compresslevel=None, *, strict_timestamps=True):\n        \"\"\"Open the ZIP file with mode read 'r', write 'w', exclusive create 'x',\n        or append 'a'.\"\"\"\n        if mode not in ('r', 'w', 'x', 'a'):\n            raise ValueError(\"ZipFile requires mode 'r', 'w', 'x', or 'a'\")\n    \n        _check_compression(compression)\n    \n        self._allowZip64 = allowZip64\n        self._didModify = False\n        self.debug = 0  # Level of printing: 0 through 3\n        self.NameToInfo = {}    # Find file info given name\n        self.filelist = []      # List of ZipInfo instances for archive\n        self.compression = compression  # Method of compression\n        self.compresslevel = compresslevel\n        self.mode = mode\n        self.pwd = None\n        self._comment = b''\n        self._strict_timestamps = strict_timestamps\n    \n        # Check if we were passed a file-like object\n        if isinstance(file, os.PathLike):\n            file = os.fspath(file)\n        if isinstance(file, str):\n            # No, it's a filename\n            self._filePassed = 0\n            self.filename = file\n            modeDict = {'r' : 'rb', 'w': 'w+b', 'x': 'x+b', 'a' : 'r+b',\n                        'r+b': 'w+b', 'w+b': 'wb', 'x+b': 'xb'}\n            filemode = modeDict[mode]\n            while True:\n                try:\n>                   self.fp = io.open(file, filemode)\nE                   FileNotFoundError: [Errno 2] No such file or directory: 'H:\\\\Git_projekty\\\\Api using python\\\\test_data.xlsx'\n\nC:\\Users\\jacek\\AppData\\Local\\Programs\\Python\\Python310\\lib\\zipfile.py:1249: FileNotFoundError"}, "start": 1669149473136, "stop": 1669149473138, "uuid": "7d783e45-efcc-4310-ae4c-48f00f3d4254", "historyId": "68e2702d2c65724908f7024373d38de8", "testCaseId": "a7df2f774c5f7ceae71f16d57e6caa86", "fullName": "TestSMS.DataDriven.test_case#test_add_students_ddt_2", "labels": [{"name": "parentSuite", "value": "TestSMS.DataDriven"}, {"name": "suite", "value": "test_case"}, {"name": "host", "value": "DESKTOP-3351BCE"}, {"name": "thread", "value": "1952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestSMS.DataDriven.test_case"}]}