{"name": "test_tc_003_Login_Invalid_Testing", "status": "failed", "statusDetails": {"message": "AssertionError: To nie jest Testing\nassert 'Testing' != 'Testing'", "trace": ">   ???\nE   AssertionError: To nie jest Testing\nE   assert 'Testing' != 'Testing'\n\nH:\\Git_projekty\\Api using python\\Pytest_learning.py\\Automation_Cases\\test_tc_001.py:17: AssertionError"}, "start": 1668965432821, "stop": 1668965432822, "uuid": "6b2974cc-239e-4364-8a11-d565baaa168a", "historyId": "9c680ba018acc55b4ad032dcc9d08768", "testCaseId": "19d26ee04f11a33b534eeedd344eb476", "fullName": "test_tc_001#test_tc_003_Login_Invalid_Testing", "labels": [{"name": "tag", "value": "Regression"}, {"name": "tag", "value": "Sanity"}, {"name": "suite", "value": "test_tc_001"}, {"name": "host", "value": "DESKTOP-3351BCE"}, {"name": "thread", "value": "1612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_tc_001"}]}